# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         promessaging-MRS
version:      1.01
version_from: lib/promessaging/MRS.pm
installdirs:  site
requires:
    SOAP::Lite:                    0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
